### PR TITLE
Make SecurityQuestion ActiveRecord class optional

### PR DESCRIPTION
**Pull request by monfresh**
The SecurityQuestion class is empty, and it's only needed if the `:security_questionable` option is turned on. Therefore, I think it should be up to the user to create the model if they need it.

The problem with automatically creating and requiring the model is that it will override a class by the same name. I have my own implementation of security questions in my app, and was going crazy trying to figure out why the code I put in my `SecurityQuestion` class wasn't being recognized.

### CODE REVIEW

**Comment by evan-007** [comment]
:+1:  just ran into this exact issue with one of our apps.

**Comment by monfresh** [comment]
Hello, and Happy New Year! Any thoughts on this PR? Is this project still being maintained? Thanks!

**Comment by monfresh** [comment]
Hello. Thoughts on this PR?

**Comment by evan-007** [comment]
I would love to see this merged as well. We've forked your branch and have been using it for this change since May of last year, thanks @monfresh.

**Comment by monfresh** [comment]
It looks like this was actually fixed at some point. The model was renamed to [SecurityQuestionable](https://github.com/phatworx/devise_security_extension/blob/master/lib/devise_security_extension.rb#L97). The git history seems to be messed up so I can't tell exactly what commit changed this.

**Comment by monfresh** [comment]
I was wrong. I was looking at the wrong thing. This issue still needs to be fixed. Re-opening my PR. @traxanos please consider merging this. Thanks!

**Comment by monfresh** [comment]
Yay! Thanks!

**Pull request merged**
