### PR TITLE
Replace Fixnum references

### LINKED ISSUE #231: Fixnum is deprecated as of Ruby 2.4.0
```
lib/devise_security_extension/models/password_expirable.rb:16: warning: constant ::Fixnum is deprecated
```

### PR DESCRIPTION
**Pull request by 3zcurdia**
It replaces references Fixnum references from ruby 2.4.
It closes #231

### CODE REVIEW

**Comment by Gasparila** [comment]
@alexdreher any way we can get this merged?

**Comment by vimutter** [comment]
@3zcurdia I think you need to update Gemfile for 2.4. Do you need help with that?

**Comment by erolms** [comment]
Folks, when can we get this commit merged into master?

**Comment by Gasparila** [comment]
Until this is merged, we "fixed" the deprecation warnings by adding `Devise::Models::PasswordArchivable.const_set("Fixnum", Integer)` to the devise initializer file

**Comment by erolms** [comment]
In my case I had to add `Devise::Models::PasswordExpirable.const_set("Fixnum", Integer)` too. Working like a charm, thanks!

**Comment by 3zcurdia** [comment]
closing this PR in favor of #238

**Pull request closed without merging**
