### PR TITLE
Rails5 deprecation fixes

### PR DESCRIPTION
**Pull request by natebird**
This pull request fixes a lot of deprecation warnings generated by Rails 5.x.

### CODE REVIEW

**Comment by ACPK** [comment]
+ 1

**Comment by manno** [comment]
Tried to rebase this one, but afterwards the tests were failing.

**Comment by natebird** [comment]
Not sure if that rebase went how it was supposed to but all the changes are there and everything is passing now.

**Comment by mathieujobin** [comment]
:+1:

**Pull request merged**
