### PR TITLE
Moving captcha and security_question into before_action

### PR DESCRIPTION
**Pull request by MikeRogers0**
It follows the example of
https://github.com/plataformatec/devise/wiki/How-To:-Use-Recaptcha-with-Devise where we use a before action, instead of overriding the create method.

I'm not 100% the best way to test this functionality, but would love to be pointed in the right direction :)

### CODE REVIEW

**Comment by manno** [comment]
Thanks! I'm not using the captcha module, but I'm going to take a look at this PR to get it merged.

**Comment by manno** [comment]
This really dries up the captcha and security questions controllers. However without tests or at least a project that uses these extensions, I don't feel comfortable merging this.

**Comment by MikeRogers0** [comment]
> without tests [...] I don't feel comfortable

I'm happy to write tests around it if you can point me in the right direction of how to test it (I couldn't see tests around the current implementation).

**Comment by manno** [comment]
Sadly there are no tests for the current implementation :(
I would try to test it like this: [test/test_password_expired_controller.rb](https://github.com/phatworx/devise_security_extension/blob/master/test/test_password_expired_controller.rb)

**Comment by MikeRogers0** [comment]
Awesome! I'll bump reopen when the tests are done :)

**Comment by MikeRogers0** [comment]
Btw reopened in #166

**Pull request closed without merging**
