### PR TITLE
reset code after several faild attempts

### PR DESCRIPTION
**Pull request by equivalent**
After several failed attempts, reset paranoid_verification_code

protection against brute force

### CODE REVIEW

**Comment by traxanos** [comment]
it's not better to clear the token?

**Comment by equivalent** [comment]
it's not better to clear the token?

theoretically I can sign-out a user, or lock his account, however that adds a dependency to other Devise modules (which theoretically may not be used). My call was for really simple regeneration of verification code, I'm not saying it's best one but best for now.

**Comment by equivalent** [comment]
you should not give some information about brute force protection

should I remove that from the view ?

**Comment by traxanos** [comment]
Under the aspect of safety, i think it was better to remove. you can readd it in you custom screen if you needed, or?

**Comment by equivalent** [comment]
I agree with with that, I'll just create Wiki entry so if anyone need similar functionality he/she may use it 

I'll fix it in next pull request

**Comment by equivalent** [comment]
https://github.com/phatworx/devise_security_extension/pull/121

**Pull request merged**
